name: Build

on: [push, pull_request]

env:
  PUBLIC_SUPABASE_URL: 'https://fake_test_url.supabase.co'
  PUBLIC_SUPABASE_ANON_KEY: 'fake_anon_key'
  PRIVATE_SUPABASE_SERVICE_ROLE: 'fake_service_role'
  PRIVATE_STRIPE_SECRET_KEY: 'fake_stripe_api_key'
  PRIVATE_NOTIFICATIONS_EMAIL: 'fake_notifications_email'
  PRIVATE_SMTP_HOST: 'fake_smtp_host'
  PRIVATE_SMTP_PORT: 'fake_smtp_port'
  PRIVATE_SMTP_USER: 'fake_smtp_user'
  PRIVATE_SMTP_PASSWORD: 'fake_smtp_pass'
  PRIVATE_ADMIN_EMAIL: 'fake_admin_email@example.com'
  PRIVATE_FROM_ADMIN_EMAIL: 'fake_from_admin_email@example.com'
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: NPM install
        run: npm ci

      - name: SvelteKit Build
        run: npm run build
